#!/usr/bin/env node
/**
 * Embeds assets/openkt-hook.sh and the openkt skill (plugin/skills/openkt, the one skill this repository ships) into
 * src/assets.generated.ts, so the package works the same from dist/, from an esbuild bundle inside the desktop app,
 * and from tests. The file is generated (not committed) by build, typecheck, pretest and the desktop bundle step, so
 * an edit to the skill or the script can never ship stale. `--check` fails when the file is stale.
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const skillDir = join(root, '../../plugin/skills/openkt');
const out = join(root, 'src/assets.generated.ts');

function walk(dir) {
  return readdirSync(dir).sort().flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

const script = readFileSync(join(root, 'assets/openkt-hook.sh'), 'utf8');
const version = Number(/^# openkt-hook-version: (\d+)$/m.exec(script)?.[1] ?? NaN);
if (!Number.isInteger(version)) throw new Error('assets/openkt-hook.sh has no "# openkt-hook-version: N" line');
const skill = Object.fromEntries(walk(skillDir).map((p) => [relative(skillDir, p).split('\\').join('/'), readFileSync(p, 'utf8')]));

const body = `// Generated by scripts/embed-assets.mjs from assets/openkt-hook.sh and plugin/skills/openkt. Do not edit.
export const HOOK_SCRIPT_VERSION = ${version};
export const HOOK_SCRIPT: string = ${JSON.stringify(script)};
/** plugin/skills/openkt, path → content. */
export const SKILL_FILES: Record<string, string> = ${JSON.stringify(skill, null, 2)};
`;

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(out, 'utf8');
  } catch {}
  if (current !== body) {
    console.error('src/assets.generated.ts is out of date: run `npm run embed -w @openkt/connect`');
    process.exit(1);
  }
} else {
  writeFileSync(out, body);
  console.log(`embedded openkt-hook.sh v${version} and ${Object.keys(skill).length} skill files`);
}
